const assert = require('node:assert/strict');
const { campaignState, filterSystems } = require('../public/assets/js/public-tools.js');
const now = Date.parse('2026-10-07T01:00:00Z');
const payload = { ok:true, meta:{last_success_at:'2026-10-07T00:59:00Z'}, data:{campaigns:[{id:1,state:'ACTIVE',ended_at:'2026-10-01T00:00:00Z'},{id:2,state:'FORECAST',ended_at:null}],systems:[]}};
assert.equal(campaignState(payload,now).fresh,true);
assert.equal(campaignState(payload,now).campaign.id,2);
assert.equal(campaignState({...payload,meta:{...payload.meta,stale:true}},now).fresh,false);
assert.equal(campaignState({...payload,meta:{last_success_at:'2026-10-06T00:00:00Z'}},now).fresh,false);
assert.equal(campaignState({...payload,meta:{last_success_at:'2026-10-08T00:00:00Z'}},now).fresh,false);
assert.equal(campaignState({...payload,meta:{}},now).fresh,false);
assert.equal(campaignState({...payload,data:{campaigns:[],systems:[]}},now).campaign,null);
assert.throws(()=>campaignState({ok:false},now));
const systems=[{name:'Akidagi',corruption_stage:2,suppression_stage:1},{name:'Enaluri',corruption_stage:5,suppression_stage:0},{name:'Taisy',corruption_stage:null,suppression_stage:null},{name:'Test',corruption_stage:2,suppression_stage:5}];
assert.deepEqual(filterSystems(systems,'aki','push').map(s=>s.name),['Akidagi']);
assert.deepEqual(filterSystems(systems,'','push').map(s=>s.name),['Akidagi']);
assert.deepEqual(filterSystems(systems,'','won').map(s=>s.name),['Enaluri']);
assert.equal(filterSystems(systems,'no match','all').length,0);
assert.equal(filterSystems(systems,'','all').length,4);
console.log('Public campaign freshness, ended campaigns and system filters passed.');
