const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const context = {document: {querySelectorAll: () => []}};
vm.createContext(context);
vm.runInContext(fs.readFileSync(require('path').join(__dirname, '../public/assets/js/pilot-data.js'), 'utf8'), context);
const row = (id, name, standing, search = name) => ({dataset:{id:String(id), name, standing:String(standing), search}});
const a = row(500010, 'Guristas Pirates', 3.98);
const b = row(500001, 'Caldari State', -1.96);
assert(context.pilotStandingCompare(a,b,'standing-desc') < 0);
assert(context.pilotStandingCompare(a,b,'standing-asc') > 0);
assert(context.pilotStandingCompare(a,b,'id-asc') > 0);
assert(context.pilotStandingCompare(a,b,'id-desc') < 0);
assert(context.pilotStandingCompare(a,b,'name') > 0);
const agent = row(3019356, 'Sister Alitura', 0, 'Sister Alitura 3019356 Sisters of EVE Servant Sisters of EVE Arnon Security');
assert(context.pilotStandingMatches(agent,' arnon ','all'));
assert(context.pilotStandingMatches(agent,'3019356','neutral'));
assert(!context.pilotStandingMatches(agent,'','positive'));
assert(!context.pilotStandingMatches(agent,'','negative'));
assert(context.pilotStandingMatches(a,'guristas','positive'));
assert(!context.pilotStandingMatches(b,'guristas','all'));
console.log('PASS: default standing order, ID/name ordering, case-insensitive affiliation/base search and positive/negative/zero filters.');
