<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/app/services/PilotCombat.php';
require_once dirname(__DIR__) . '/app/services/PilotRomance.php';
require_once dirname(__DIR__) . '/app/services/PilotInsurgency.php';
require_once dirname(__DIR__) . '/app/services/GuristasDashboard.php';
function expansion_check(bool $ok, string $label): void { if (!$ok) throw new RuntimeException($label); }
function expansion_throws(callable $fn, string $label): void { try { $fn(); } catch (Throwable $e) { return; } throw new RuntimeException($label); }
$dir = sys_get_temp_dir() . '/guristas-expansion-' . bin2hex(random_bytes(8));
$store = new GuristasPilotRecordStore($dir . '/records');
$record = $store->read(101);
$record = $store->update(101, static function ($r) { return eve_romance_transition($r, 'romance_start'); });
foreach (['honest','open','together'] as $chapter => $choice) $record = $store->update(101, static function ($r) use ($chapter,$choice) { return eve_romance_transition($r,'romance_choice',$choice,$chapter); });
expansion_check($record['romance']['affinity'] === 100 && $record['romance']['chapter'] === 3, 'Saved romance progression');
expansion_throws(fn()=>$store->update(101, fn($r)=>eve_romance_transition($r,'romance_choice','honest',0)), 'No repeated scene farming');
expansion_check($store->read(202)['romance']['chapter'] === 0, 'Character story isolation');
$paused = $store->update(101, fn($r)=>eve_romance_transition($r,'romance_pause'));
expansion_check(!$paused['romance']['enabled'] && $paused['romance']['affinity'] === 100, 'Pause retains progress');
expansion_throws(fn()=>$store->update(101, fn($r)=>eve_romance_transition($r,'romance_choice','together',3)), 'Invalid completion choices rejected');
$mail = ['killmail_id'=>9001,'killmail_time'=>gmdate('c'),'solar_system_id'=>30000142,'victim'=>['character_id'=>999,'ship_type_id'=>587], 'attackers'=>[['character_id'=>101,'ship_type_id'=>17930,'final_blow'=>false]]];
expansion_check(eve_guristas_kill_evidence($mail,101,eve_guristas_hulls())['hull_id'] === 17930, 'Attacker hull, not victim hull');
expansion_check(eve_guristas_kill_evidence($mail,202,eve_guristas_hulls()) === null,'Another character receives no credit');
$loss = $mail; $loss['victim']['character_id']=101;
expansion_check(eve_guristas_kill_evidence($loss,101,eve_guristas_hulls()) === null,'Loss excluded');
$npc=$mail; unset($npc['victim']['character_id']);
expansion_check(eve_guristas_kill_evidence($npc,101,eve_guristas_hulls()) === null,'NPC/structure excluded');
$other=$mail; $other['attackers'][0]['ship_type_id']=587;
expansion_check(eve_guristas_kill_evidence($other,101,eve_guristas_hulls()) === null,'Other hull excluded');
$config = require dirname(__DIR__).'/config/esi.php'; $calls=[]; $denied=false; $status=200;
$transport = static function ($url,$headers) use (&$calls,&$status,$mail) {
    $calls[]=[$url,$headers];
    $private = str_contains($url,'/characters/');
    $data = $private ? [['killmail_id'=>9001,'killmail_hash'=>str_repeat('a',40)]] : $mail;
    return ['status'=>$status,'body'=>json_encode($data),'headers'=>['cache-control'=>'max-age=300','x-pages'=>'2']];
};
$authorize = static function ($id,$scope) use (&$denied) { if ($denied) throw new GuristasAuthorizationRequired('Denied'); return ['token'=>'fixture-secret','identity'=>'test|'.$id]; };
$client = new GuristasEsiClient($config,new GuristasEsiCache($dir.'/cache'),$transport);
$combat = new GuristasPilotCombat($client,$store,$authorize);
$a=$combat->read(101);
expansion_check($a['state']==='ready' && count($a['data']['kills'])===1,'Imported verified kill');
expansion_check(count($calls)===3 && str_contains($calls[1][0],'page=2'),'Paginated recent history');
expansion_check(!str_contains(implode(' ',$calls[2][1]),'fixture-secret'),'Public killmail lookup carries no bearer');
$b=$combat->read(101); expansion_check(count($b['data']['kills'])===1 && count($calls)===3,'Deduplication and cache reuse');
$denied=true;$c=$combat->read(101);
expansion_check($c['state']==='authorization_required' && $c['data']===null && count($calls)===3,'Revoked permission hides persisted evidence without network');
$denied=false;$snapshot=$combat->read(101,false);
expansion_check($snapshot['state']==='recorded' && count($snapshot['data']['kills'])===1 && count($calls)===3,'Overview uses authorized snapshot without import');
$unstarted=$combat->read(202,false); expansion_check($unstarted['data']===null,'Unsynchronized history is not zero');
$now=time();$overlay=['data'=>['campaigns'=>[['id'=>10,'state'=>'ACTIVE','origin_name'=>'Akidagi','ended_at'=>null]],'systems'=>[
 ['name'=>'A','corruption_stage'=>2,'corruption_percent'=>35,'suppression_stage'=>1],['name'=>'B','corruption_stage'=>2,'corruption_percent'=>39,'suppression_stage'=>2],['name'=>'Blocked','corruption_stage'=>2,'corruption_percent'=>40,'suppression_stage'=>5],['name'=>'C','corruption_stage'=>4,'corruption_percent'=>90,'suppression_stage'=>0]]], 'meta'=>['last_success_at'=>gmdate('c',$now),'stale'=>false]];
expansion_check(eve_insurgency_advice($overlay,$now)['target']===null,'Unknown travel cannot identify best destination');
foreach ($overlay['data']['systems'] as $i => &$system) $system['system_id'] = $i + 1; unset($system);
expansion_check(eve_insurgency_advice($overlay,$now,['travel'=>['fw_jumps'=>[1=>1,2=>5,3=>0,4=>6]]])['target']['name']==='A','Nearby practical target beats distant progress; suppression-five excluded');
$overlay['meta']['stale']=true;expansion_check(eve_insurgency_advice($overlay,$now)['phase']==='unavailable','Stale campaign cannot direct travel');$overlay['meta']['stale']=false;
$overlay['data']['campaigns'][0]=['id'=>11,'state'=>'FORECAST','started_at'=>gmdate('c',$now),'ended_at'=>null];
expansion_check(strtotime(eve_insurgency_advice($overlay,$now)['expected_start'])===$now+172800,'48-hour forecast estimate');
$overlay['data']['campaigns']=[];expansion_check(eve_insurgency_advice($overlay,$now)['phase']==='none','Unannounced next campaign has no fabricated start');
$pilotData=['combat'=>$snapshot,'romance'=>$paused['romance']]; $d=eve_guristas_dashboard($pilotData,[]);
$earned=array_column(array_filter($d['badges'],fn($b)=>$b['earned']),'name');
expansion_check(in_array('Worm · First blood',$earned,true) && in_array('A Shared Horizon',$earned,true),'Combat and story achievements');
$friends=$paused['romance'];$friends['choices'][2]='friends';$pilotData['romance']=$friends;
$d=eve_guristas_dashboard($pilotData,[]);foreach($d['badges'] as $badge)if($badge['name']==='A Shared Horizon')expansion_check(!$badge['earned'],'Friend ending does not earn romance partner');
require_once dirname(__DIR__) . '/app/services/FrontlinesService.php';
$reflection = new ReflectionClass(GuristasFrontlinesService::class);$frontlines=$reflection->newInstanceWithoutConstructor();$parse=$reflection->getMethod('parseGuristasSystems');$parse->setAccessible(true);
$fixture=json_decode((string)file_get_contents(__DIR__.'/fixtures/frontlines-campaigns.json'),true);$parsed=$parse->invoke($frontlines,$fixture);
expansion_check(count($parsed['campaigns'])===1 && $parsed['campaigns'][0]['state']==='ACTIVE','Preserve only Guristas campaign metadata');
$account=file_get_contents(dirname(__DIR__).'/public/account/index.php');
expansion_check(str_contains($account,"eve_require_csrf") && str_contains($account,"'combat' => 'Guristas Hulls'") && str_contains($account,"'romance' => 'Romance'"),'New account sections and CSRF gating');
// Render the new sections without a database or live API.
mkdir($dir . '/sessions'); session_save_path($dir . '/sessions'); eve_session();
$pilotData = ['combat' => $snapshot, 'romance' => $record['romance']];
ob_start(); require dirname(__DIR__) . '/app/views/partials/pilot-combat.php'; $combatHtml = ob_get_clean();
expansion_check(str_contains($combatHtml, 'Worm') && str_contains($combatHtml, '9001') && !str_contains($combatHtml, 'NEXT '), 'Combat section renders evidence without action cards');
ob_start(); require dirname(__DIR__) . '/app/views/partials/pilot-romance.php'; $romanceHtml = ob_get_clean();
expansion_check(str_contains($romanceHtml, 'A shared horizon') && str_contains($romanceHtml, 'name="csrf"'), 'Saved ending and protected story forms render');
$dashboard = ['fw_ready' => true, 'enlisted' => true];
$insurgencyAdvice = ['phase' => 'active', 'campaign' => ['id' => 10, 'origin_name' => 'Akidagi', 'corruption_target' => 10], 'target' => ['name' => '<unsafe>', 'corruption_stage' => 2, 'corruption_percent' => 39, 'suppression_stage' => 0], 'goal' => 'spread'];
ob_start(); require dirname(__DIR__) . '/app/views/partials/pilot-insurgency-action.php'; $actionHtml = ob_get_clean();
expansion_check(str_contains($actionHtml, '&lt;unsafe&gt;') && str_contains($actionHtml, 'insurgency.svg') && str_contains($actionHtml, 'stage 3'), 'Escaped illustrated live action');
require_once dirname(__DIR__) . '/app/services/PilotHullGoal.php';
$goalData = ['combat' => ['data' => ['kills' => [
 ['hull_id'=>78367,'time'=>'2026-10-05T12:00:00Z'], ['hull_id'=>78367,'time'=>'2026-10-06T12:00:00Z'], ['hull_id'=>17930,'time'=>'2026-10-06T13:00:00Z']]]]];
$goalData['skills'] = ['state' => 'ready', 'data' => array_fill_keys(array_keys(eve_readiness_reference()['types']), 5)];
$goal = eve_guristas_hull_goal($goalData);
expansion_check($goal['id'] !== null && $goal['target'] === 10 && $goal['remaining'] === 7, 'Skill-qualified hull and combined overall progress');
$emptyGoal = eve_guristas_hull_goal([]);
expansion_check($emptyGoal['id'] === null && !$emptyGoal['history_available'] && $emptyGoal['remaining'] === null, 'Missing skills/history never invent readiness or progress');
$goalData['combat']['data']['kills'] = array_fill(0,500,['hull_id'=>17930,'time'=>'2026-10-06T14:00:00Z']);
expansion_check(eve_guristas_hull_goal($goalData)['target'] === null, 'No invented achievement above configured tier');
session_write_close();
file_put_contents($dir . '/records/202.json', '{broken');
expansion_throws(fn() => $store->read(202), 'Corrupt story is not silently reset');
foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST) as $file) { if($file->isDir())rmdir($file->getPathname());else unlink($file->getPathname()); }rmdir($dir);
echo "PASS: private story persistence, replay rejection, hull kill evidence, pagination, deduplication, permission revocation, campaign freshness/forecasting, and new achievements.\n";
