<?php
$pageTitle = 'Guristas Supply Console';
$pageDescription = 'Price your next build, compare a realistic batch, or work out what your Commando Guri LP could earn. Open to every capsuleer.';
$navActive = 'build';
require dirname(__DIR__, 2) . '/app/views/partials/public-tool-header.php';
require_once dirname(__DIR__, 2) . '/app/services/PublicIndustry.php';
$reference = guri_industry_reference();
$views = ['build'=>'Production','lp'=>'Commando Guri LP','trade'=>'Market comparison','fulcrum'=>'The Fulcrum'];
$view = is_string($_GET['view'] ?? null) && isset($views[$_GET['view']]) ? $_GET['view'] : 'build';
$bpId = is_string($_GET['bp'] ?? null) && isset($reference['blueprints'][$_GET['bp']]) ? $_GET['bp'] : '17931';
$typeId = is_string($_GET['type'] ?? null) && isset($reference['types'][$_GET['type']]) ? (int)$_GET['type'] : 17930;
$blueprints = $reference['blueprints']; uasort($blueprints, static function ($a,$b) { return strcasecmp($a['name'],$b['name']); });
$types = $reference['types']; uasort($types, static function ($a,$b) { return strcasecmp($a['name'],$b['name']); });
?>
<nav class="field-tabs" aria-label="Supply tools"><?php foreach ($views as $key=>$label): ?><a href="?view=<?= $key ?>" <?= $view === $key ? 'aria-current="page"' : '' ?>><?= $label ?></a><?php endforeach; ?></nav>
<?php if ($view === 'build'): ?>
<section class="tool-card" data-build><h2>Price a build before committing</h2><p>Choose a recipe and the efficiencies shown in EVE. Then add material prices and the rest of the job costs. Owned materials still have a replacement or sale value.</p><div class="tool-controls"><label>Blueprint<select data-build-blueprint><?php foreach ($blueprints as $id=>$bp): ?><option value="<?= (int)$id ?>" <?= (string)$id === $bpId ? 'selected' : '' ?>><?= escape($bp['name']) ?></option><?php endforeach; ?></select></label><label>Runs<input type="number" data-build-runs min="1" max="10000" value="1"></label><label>Blueprint ME %<input type="number" data-build-me min="0" max="10" value="0"></label><label>Blueprint TE %<input type="number" data-build-te min="0" max="20" value="0"></label></div>
<details><summary>Facility and trained skill reductions</summary><div class="tool-controls"><label>Combined facility material reduction %<input type="number" data-build-facility min="0" max="90" step="0.01" value="0"></label><label>Industry skill level<input type="number" data-build-industry min="0" max="5" value="0"></label><label>Advanced Industry level<input type="number" data-build-advanced min="0" max="5" value="0"></label><label>Other combined time reduction %<input type="number" data-build-time min="0" max="90" step="0.01" value="0"></label></div><p class="tool-note">Use the combined facility/rig bonus, not a sum of separate percentages. Defaults apply no unverified station bonus. Other time reduction excludes the skills and TE entered above.</p></details>
<div class="tool-controls"><label>Price materials at<select data-build-hub><?php foreach ($reference['hubs'] as $key=>$hub): ?><option value="<?= escape($key) ?>"><?= escape($hub['name']) ?></option><?php endforeach; ?></select></label></div><div class="tool-buttons"><button type="button" data-build-price>Get batch material prices</button></div><p data-build-price-status role="status">Prices are blank until you request them or enter your own.</p><p data-build-summary role="status"></p><div class="tool-table-wrap"><table class="tool-table"><caption>Materials for the complete job</caption><thead><tr><th>Material</th><th>Quantity</th><th>ISK per unit</th><th>Cost</th></tr></thead><tbody data-build-materials></tbody></table></div>
<div class="tool-controls"><label>Job installation, blueprint acquisition &amp; other batch costs<input type="number" data-build-other min="0" step="0.01" value="0"></label><label>Sale price per finished unit<input type="number" data-build-sale min="0" step="0.01" placeholder="Optional, to compare surplus"></label><label>Sale tax + broker fees %<input type="number" data-build-fees min="0" max="100" step="0.01" value="0"></label><label>Hauling and expected loss allowance for this batch<input type="number" data-build-haul min="0" step="0.01" value="0"></label></div>
<p class="tool-status" data-build-result role="status">Enter all material prices to calculate the batch.</p><p class="tool-note">Zero fees and other costs mean a gross estimate. Verify the actual job in EVE before submitting. This does not confirm blueprint ownership, skills, available runs, facility access or market demand.</p><div class="tool-buttons"><a data-build-market href="?view=trade">Compare finished-product orders</a><button type="button" data-build-copy>Copy material shopping list</button></div><p data-build-copy-status role="status"></p><a href="https://support.eveonline.com/hc/en-us/articles/203210542-Material-Efficiency-Research" target="_blank" rel="noopener noreferrer">Official material rules ↗</a></section>
<?php elseif ($view === 'lp'): ?>
<section class="tool-card" data-lp><h2>Choose how to spend Commando Guri LP</h2><p>Use this as a conversion ledger, without connecting your wallet or LP balance. Compare what you can actually sell after every required cost.</p><p class="tool-note" data-offer-freshness>Offer reference retrieved <?= escape($reference['retrieved_at']) ?>. Refresh before making a purchase.</p><div class="tool-buttons"><button type="button" data-offer-refresh>Refresh offers from EVE</button></div><div class="tool-controls"><label>Find an offer<input type="search" data-offer-search placeholder="Hull, implant, booster or module"></label><label>Offer<select data-lp-offer></select></label></div><div data-lp-details></div><div class="tool-controls"><label>Net proceeds from selling the entire offer output<input type="number" data-lp-proceeds min="0" step="0.01" placeholder="After sales tax and broker fees"></label><label>Required-item replacement cost for the offer<input type="number" data-lp-required min="0" step="0.01" placeholder="Use 0 only if no items required"></label><label>Manufacturing, hauling and other conversion costs<input type="number" data-lp-other min="0" step="0.01" placeholder="Include blueprint manufacturing when applicable"></label></div><p class="tool-status" data-lp-result role="status">Select an offer and enter the full conversion costs.</p><p class="tool-note">A blueprint copy is not a finished ship. Check its runs and manufacturing costs. This ledger does not assume all LP offers have a market or that listed sale prices will be achieved. Offers requiring another currency must be valued before comparison.</p></section>
<?php else: ?>
<section class="tool-card" data-market data-market-mode="<?= $view ?>"><h2><?= $view === 'fulcrum' ? 'Check The Fulcrum before hauling' : 'Compare a batch, not one attractive price' ?></h2><p><?= $view === 'fulcrum' ? 'See station-listed sell stock and immediate buy-order demand. A low stock count is not a supply contract or a promise somebody will buy your cargo.' : 'Choose an item and quantity. Quotes consume order depth for that batch, using orders listed at each supported NPC station.' ?></p><div class="tool-controls"><label>Item<select data-market-type><?php foreach ($types as $id=>$type): ?><option value="<?= (int)$id ?>" <?= $typeId === (int)$id ? 'selected' : '' ?>><?= escape($type['name']) ?></option><?php endforeach; ?></select></label><label>Batch quantity<input type="number" data-market-quantity min="1" max="1000000000" value="1"></label></div><div class="tool-buttons"><button type="button" data-market-refresh>Check station orders</button></div><p data-market-status role="status">Choose a batch, then contact the market relay.</p><div class="tool-table-wrap"><table class="tool-table"><caption>Immediate station transactions, before your fees and hauling</caption><thead><tr><th>Station</th><th>Buy entire batch</th><th>Sell entire batch</th><th>Sell stock / buy demand</th><th>Quote status</th></tr></thead><tbody data-market-rows></tbody></table></div>
<?php if ($view === 'trade'): ?><div class="tool-controls"><label>Buy at<select data-trade-buy><?php foreach ($reference['hubs'] as $key=>$hub): ?><option value="<?= escape($key) ?>"><?= escape($hub['name']) ?></option><?php endforeach; ?></select></label><label>Sell into buy orders at<select data-trade-sell><?php foreach ($reference['hubs'] as $key=>$hub): ?><option value="<?= escape($key) ?>" <?= $key === 'dodixie' ? 'selected' : '' ?>><?= escape($hub['name']) ?></option><?php endforeach; ?></select></label><label>Sales tax %<input type="number" data-trade-tax min="0" max="100" step="0.01" value="0"></label><label>Hauling, expected losses &amp; other batch costs<input type="number" data-trade-cost min="0" step="0.01" value="0"></label></div><p class="tool-status" data-trade-result role="status">Check both stations for the complete quantity first.</p><?php endif; ?>
<p class="tool-note">Regional daily trade volume describes the whole region, not this station. Missing history is unknown turnover. Ranged buy orders listed elsewhere and private Upwell markets are excluded. Orders can change while you travel. The site does not know competition, route safety or whether you can reach either station. Quotes are not guaranteed fills. A broker fee is normally a separate concern when creating your own order; these quotes use existing orders.</p><a href="/operations/#supply">Check posted supply jobs →</a> · <a href="/war/guristas/">Plan your next sortie →</a></section>
<?php endif; ?>
<noscript><p class="tool-status">JavaScript is needed for calculations and market requests. Open the Industry, Market and LP Store windows in EVE for the same task.</p></noscript>
<p class="tool-note">Static recipes: CCP build <?= (int)$reference['sde_build'] ?>, released <?= escape($reference['sde_release']) ?>. Costs are estimates for your entered assumptions, not personal account records.</p>
<script type="application/json" id="industry-reference"><?= json_encode($reference, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?></script><script src="/assets/js/public-industry.js?v=<?= filemtime(dirname(__DIR__) . '/assets/js/public-industry.js') ?>" defer></script>
<?php require dirname(__DIR__, 2) . '/app/views/partials/public-tool-footer.php'; ?>
