<?php
header('Cache-Control: private, no-store');
require_once dirname(__DIR__,2).'/services/CommunityWeb.php';require __DIR__.'/public-tool-header.php';
$failure=false;
try{$ledger=community_network()->read();}catch(Throwable $e){$failure=true;$ledger=['revision'=>0,'entries'=>[],'claims'=>[]];}
$labels=['fleet'=>'Fleets','supply'=>'Supply Jobs','report'=>'Field Reports','art'=>'Community Art','propaganda'=>'Fan Propaganda','comic'=>'Comics','broadcast'=>'Broadcast Archive'];
$help=['fleet'=>'No departures posted. Open the War Room for the current campaign and use the in-game militia channels to find a fleet.','supply'=>'No orders posted. Check Fulcrum stock before hauling. A market listing does not promise a sale.','report'=>'No field reports published yet. Officers can post a verified account of an operation here.','propaganda'=>'No approved propaganda images published yet. Submit original artwork, credit its creator and mark it as fan propaganda.','art'=>'No approved art published yet. Sign in to submit your work for review.','comic'=>'No comic episodes published yet. Creators can submit ordered pages and transcripts for review.','broadcast'=>'No recordings published yet. Open Signals for Kniraven’s channel and pirate radio.'];
?>
<p class="tool-buttons"><a href="/operations/">Operations</a><a href="/community/">Transmissions</a><a href="/industry/?view=fulcrum">Fulcrum market</a><a href="/signals/">Radio &amp; live channel</a><?php if($navActive==='community'): ?><a href="/community/submit.php">Submit art or a comic</a><?php if($viewer): ?><a href="/community/submissions.php">Your submissions</a><?php endif; endif; ?></p>
<?php if($failure): ?><p role="alert">The board is unavailable. Existing records have not been replaced. Try again later.</p><?php endif; ?>
<?php if(isset($_SESSION['community_status'])): ?><p role="status"><?= escape((string)$_SESSION['community_status']) ?></p><?php unset($_SESSION['community_status']); endif; ?>
<nav class="field-tabs" aria-label="Board sections"><?php foreach($types as $type): ?><a href="#<?= escape($type) ?>"><?= escape($labels[$type]) ?></a><?php endforeach; ?></nav>
<?php foreach($types as $type): $entries=CommunityNetwork::published($ledger,[$type==='propaganda'?'art':$type]); if(in_array($type,['art','propaganda'],true))$entries=array_values(array_filter($entries,fn($e)=>($e['category']??'fan-art')===($type==='propaganda'?'propaganda':'fan-art'))); if(in_array($type,['fleet','supply'],true)){$entries=array_values(array_filter($entries,fn($e)=>$e['status']==='published' && ($e['when']==='' || $e['when']>=gmdate('Y-m-d\TH:i'))));usort($entries,fn($a,$b)=>strcmp($a['when']?:'9999',$b['when']?:'9999'));} ?>
<section id="<?= escape($type) ?>" class="tool-section"><h2><?= escape($labels[$type]) ?></h2>
<?php if(!$entries): ?><div class="tool-card"><p><?= escape($help[$type]) ?></p><?php if($type==='fleet'): ?><a href="/war/guristas/">Open the War Room</a><?php elseif(in_array($type,['art','propaganda','comic'],true)): ?><a href="/community/submit.php">Send your work for review</a><?php endif; ?></div><?php endif; ?>
<div class="tool-grid"><?php foreach($entries as $entry): $image=$entry['images'][0]??null; ?><article class="tool-card community-card">
<?php if($image): ?><a href="<?= escape(community_entry_url($entry)) ?>"><img class="community-thumbnail" loading="lazy" src="/community/media.php?id=<?= escape($image['id']) ?>" alt="<?= escape($entry['title']) ?>" width="<?= (int)$image['width'] ?>" height="<?= (int)$image['height'] ?>"></a><?php endif; ?>
<h3><?= escape($entry['title']) ?></h3><p><?= escape(preg_match('/^.{0,240}/us',$entry['body'],$match)?$match[0]:$entry['body']) ?><?= strlen($entry['body'])>strlen($match[0]??$entry['body'])?'…':'' ?></p>
<?php if($entry['credit']): ?><p>By <?= escape($entry['credit']) ?></p><?php endif; ?>
<?php if($entry['when']): ?><p><?= $type==='fleet'?'Departure':'Deadline' ?>: <?= escape(str_replace('T',' ',$entry['when'])) ?> UTC</p><?php endif; ?>
<?php if($entry['location']): ?><p><?= escape($entry['location']) ?></p><?php endif; ?>
<?php if($type==='supply'): $progress=CommunityNetwork::progress($ledger,$entry['id']); if($progress['target']): ?><p><?= number_format($progress['verified']) ?> / <?= number_format($progress['target']) ?> units verified · <?= number_format($progress['available']) ?> available to reserve</p><?php else: ?><p>Confirm quantity and reward with the organizer.</p><?php endif; endif; ?>
<a class="secondary-button community-card-action" href="<?= escape(community_entry_url($entry)) ?>"><?= escape(match($type){'comic'=>'Read episode','art','propaganda'=>'View artwork','report'=>'Read field report','supply'=>'Read order & reserve',default=>'Read full details'}) ?></a>
</article><?php endforeach; ?></div></section><?php endforeach; ?>
<?php if($navActive==='operations'): ?>
<section id="contributions" class="tool-section"><h2>Verified supply progress</h2><p>Only officer-approved deliveries count here. Reservations and unreviewed evidence are separate. Item quantities are tracked per order, not combined across unrelated items.</p>
<?php $jobs=CommunityNetwork::published($ledger,['supply']); if(!$jobs): ?><p>No public supply targets yet.</p><?php endif; ?>
<div class="tool-grid"><?php foreach($jobs as $job): $progress=CommunityNetwork::progress($ledger,$job['id']); ?><article class="tool-card"><h3><?= escape($job['title']) ?></h3><?php if($progress['target']): ?><p><?= number_format($progress['verified']) ?> / <?= number_format($progress['target']) ?> units of <?= escape($job['item']) ?> verified</p><progress max="<?= $progress['target'] ?>" value="<?= min($progress['target'],$progress['verified']) ?>" aria-label="<?= escape('Verified progress for '.$job['title']) ?>"></progress><?php endif; ?><p><?= $progress['deliveries'] ?> verified delivery records<?= $job['status']==='archived'?' · closed order':'' ?></p><a href="/operations/entry.php?id=<?= escape($job['id']) ?>">Order details</a></article><?php endforeach; ?></div></section>
<?php if($viewer): ?><section id="record" class="tool-section"><h2>Your supply record</h2><p>Evidence and review notes are private to you and staff. Approval does not make an automatic reward payment.</p><?php $mine=array_filter($ledger['claims'],fn($c)=>$c['actor']===(int)$viewer['character_id']); if(!$mine): ?><p>No reservations or deliveries recorded yet.</p><?php endif; ?><?php foreach(array_reverse($mine) as $claim): require __DIR__.'/supply-record.php'; endforeach; ?></section><?php endif; endif; ?>
<?php require __DIR__.'/public-tool-footer.php'; ?>
