<?php
require_once dirname(__DIR__, 2) . '/services/GuristasDashboard.php';
$dashboard = eve_guristas_dashboard($pilotData, eve_pilot_entity_catalog());
$guristas = $dashboard;
$faction = $dashboard['faction'];
$next = $dashboard['next'];
$recommended = $dashboard['recommended'];
$accountView = $accountView ?? 'overview';
require_once dirname(__DIR__, 2) . '/services/PilotHullGoal.php';
$hullGoal = eve_guristas_hull_goal($pilotData);
?>
<div class="guristas-journey">
<?php if ($accountView === 'overview'): ?><div class="dossier-heading"><div><p class="eyebrow">YOUR GURISTAS DOSSIER</p><h3>Make your next move.</h3></div><span class="dossier-status"><?= $dashboard['enlisted'] ? '● Commando Guri · enlisted' : ($dashboard['fw_ready'] ? 'Not enlisted with Guristas' : 'Enlistment unavailable') ?></span></div>
<div class="dossier-overview">
<article class="dossier-trust"><img src="https://images.evetech.net/corporations/500010/logo?size=128" width="64" height="64" alt="" loading="lazy"><div><span>Guristas faction trust</span><strong><?= $faction === null ? 'Not reported' : (($faction['effective'] ?? $faction['standing']) > 0 ? '+' : '') . number_format($faction['effective'] ?? $faction['standing'], 2) ?></strong><small><?= isset($faction['effective']) ? 'Effective standing · raw ' . number_format($faction['standing'], 2) : 'Raw standing · skill calculation unavailable' ?></small><?php if ($dashboard['best_corp'] !== null): ?><small>Strongest corporation: <?= eve_e($dashboard['best_corp']['name'] ?? 'Guristas corporation') ?> · raw <?= number_format($dashboard['best_corp']['standing'], 2) ?></small><?php endif; ?></div></article>
<article class="dossier-next"><p class="eyebrow">NEXT RECOGNITION</p>
<?php if ($next !== null): ?><h4><?= eve_e($next['name']) ?></h4><p><strong><?= number_format($next['distance'], 2) ?></strong> raw faction standing to go.</p><progress max="100" value="<?= $next['percent'] ?>" aria-label="Progress from +<?= $next['floor'] ?> to +<?= $next['threshold'] ?> raw faction standing"></progress><small><?= number_format($next['percent']) ?>% of this stage · target +<?= $next['threshold'] ?> · earns the <?= eve_e($next['name']) ?> site title</small>
<?php elseif (!$dashboard['fresh']): ?><h4>Awaiting fresh standings</h4><p>Progress and recognition need an up-to-date standings response.</p>
<?php elseif ($faction === null): ?><h4>Establish your first connection</h4><p>EVE has not reported a Guristas faction relationship. Start with a level 1 agent.</p>
<?php else: ?><h4>Maximum faction trust reached</h4><p>Your +10 faction recognition is earned. Build your agent network or put your trust to work.</p><?php endif; ?>
</article></div>
<article class="dossier-action dossier-illustrated"><img class="dossier-action-icon" src="<?= $recommended !== null && $dashboard['enlisted'] ? 'https://images.evetech.net/characters/' . $recommended['id'] . '/portrait?size=128' : '/assets/images/dossier/missions.svg' ?>" width="72" height="72" alt=""><div><p class="eyebrow">YOUR NEXT ACTION</p>
<?php if (!$dashboard['fresh']): ?><h4>Restore your standings feed</h4><p>Reload this page to check EVE again. If permission was revoked, sign in again.</p>
<?php elseif ($dashboard['faction_standing'] !== null && $dashboard['faction_standing'] < 0): ?><h4>Rebuild trust with the Pirates</h4><p>Use ordinary Guristas missions to build agent and corporation trust. Guristas storyline rewards can raise faction standing toward 0.0 for enlistment.</p>
<?php elseif (!$dashboard['enlisted'] && $dashboard['fw_ready'] && $dashboard['faction_standing'] !== null): ?><h4>Check Guristas enlistment in EVE</h4><p>Your raw faction standing meets the 0.0 threshold. Open the Insurgencies enlistment window and check the remaining requirements.</p>
<?php elseif ($recommended !== null): ?><div class="dossier-agent-intro"><div><h4>Find work with <?= eve_e($recommended['name']) ?></h4><p>Level <?= $recommended['agent_level'] ?> · <?= eve_e($recommended['division_name'] ?? 'Division not recorded') ?> · <?= eve_e($recommended['corporation_name'] ?? 'Guristas') ?>.<br>Recorded base: <?= eve_e($pilotData['entity_names'][$recommended['station_id'] ?? 0] ?? $recommended['location_name']) ?>.</p><p class="note"><?= eve_e($recommended['race_name'] ?? 'Race not recorded') ?> agent serving the Guristas Pirates<?= !empty($recommended['is_locator']) ? ', with a recorded locator service' : '' ?>. <?= ($recommended['division_name'] ?? '') === 'Security' ? 'Their Security division offers combat mission work.' : 'Prepare for the mission type shown by their division.' ?></p></div></div><p class="note"><?= $recommended['state'] === 'eligible' ? 'Calculated standing requirements met.' : ($recommended['state'] === 'level_one' ? 'Ordinary level 1 agents require no positive standing.' : 'A relationship qualifies; an unreported relationship still needs checking in EVE.') ?> Complete missions to improve agent and corporation trust. Confirm access and prepare for nullsec travel. To advance faction recognition, watch for Guristas storyline opportunities; ordinary mission rewards build agent and corporation trust.</p>
<?php else: ?><h4>Review your Guristas mission options</h4><p>Open Standings &amp; Agents and check the ordinary-agent list for the relationships or permissions you still need.</p><?php endif; ?>
<?php if ($recommended !== null): ?><details class="dossier-selection"><summary>Why this agent?</summary><p class="note"><?= eve_e($recommended['selection_reason']) ?></p><?php if ($recommended['jumps'] !== null): ?><p><?= $recommended['jumps'] ?> stargate jumps from your reported location. Shortest route, not a safety assessment.</p><?php endif; ?><?php if ($recommended['alternatives'] !== []): ?><p>Other options if access, travel or the offered mission is unsuitable:</p><ul><?php foreach ($recommended['alternatives'] as $alternative): ?><li><?= eve_e($alternative['name']) ?> · level <?= $alternative['agent_level'] ?> · <?= eve_e($alternative['system_name'] ?? $alternative['location_name']) ?><?= $alternative['jumps'] === null ? ' · travel unknown' : ' · ' . $alternative['jumps'] . ' jumps' ?></li><?php endforeach; ?></ul><?php endif; ?></details><?php endif; ?>
</div><a class="dossier-button" href="?view=standings#guristas-agent-options">View mission options ↓</a>
</article><?php require __DIR__ . '/pilot-insurgency-action.php'; ?>
<div class="dossier-secondary-actions"><article class="dossier-action dossier-illustrated"><img class="dossier-action-icon" src="<?= $hullGoal['id'] !== null ? 'https://images.evetech.net/types/' . $hullGoal['id'] . '/render?size=128' : '/assets/images/dossier/missions.svg' ?>" width="72" height="72" alt=""><div><p class="eyebrow">NEXT COMBAT ACTION</p>
<h4><?= $hullGoal['id'] === null ? 'Check your combat readiness' : ($hullGoal['first_blood'] ? 'Earn first blood in the ' : 'Build your record in the ') . eve_e($hullGoal['name']) ?></h4>
<?php if ($hullGoal['id'] !== null): ?><p>Your active skills meet this hull’s prerequisites and our basic support-skill guidance. <?= $hullGoal['readiness']['current'] ? 'You are currently flying it.' : ($hullGoal['readiness']['local'] ? 'A hull is recorded at your current location.' : ($hullGoal['readiness']['owned'] === true ? 'You own a recorded hull elsewhere.' : 'Ownership or local availability is not confirmed.')) ?></p><?php endif; ?>
<?php if ($hullGoal['first_blood']): ?><p>One recorded player kill in this hull earns its First blood recognition.</p><?php elseif ($hullGoal['remaining'] !== null): ?><p><?= $hullGoal['remaining'] ?> more recorded kills in any Guristas hull reach the <?= number_format($hullGoal['target']) ?>-kill milestone.</p><?php elseif (!$hullGoal['history_available']): ?><p>Import your kill history in Guristas Hulls to personalize your next milestone.</p><?php else: ?><p>All current overall combat milestones are reached. Explore unfinished hull recognition.</p><?php endif; ?>
<details><summary>Why this hull?</summary><p class="note"><?= eve_e($hullGoal['reason']) ?></p><?php if ($hullGoal['alternatives'] !== []): ?><p>Other skill-qualified options: <?= eve_e(implode(', ', array_column($hullGoal['alternatives'], 'name'))) ?>. Check their role and the site’s hull restrictions in EVE.</p><?php endif; ?></details><a href="?view=combat">Open Guristas hull combat →</a></div></article>
<article class="dossier-action dossier-illustrated"><img class="dossier-action-icon" src="/assets/images/dossier/romance.svg" width="72" height="72" alt=""><div><p class="eyebrow">OPTIONAL STORY ACTION</p><h4><?= ($pilotData['romance']['chapter'] ?? 0) >= 3 ? 'Your story with Ren Vey' : (!empty($pilotData['romance']['enabled']) ? 'Return to your private frequency' : 'Meet Ren Vey') ?></h4><p>An original Guristas.net romance story. Make choices, build affinity and earn relationship recognition independently of EVE standings.</p><a href="?view=romance">Open Romance →</a></div></article></div>
<?php endif; ?>
<?php if (in_array($accountView, ['overview', 'standings', 'achievements'], true)):
$achievementScope = $accountView === 'achievements' ? 'all' : ($accountView === 'overview' ? 'overview' : 'standings');
require __DIR__ . '/pilot-achievements.php';
endif; ?>
<?php if ($accountView === 'overview'): ?><aside class="dossier-guide-link"><img src="/assets/images/dossier/missions.svg" width="40" height="40" alt=""><div><strong>Discover Guristas special missions</strong><p>Keep the epic arc and COSMOS chains on your radar. Agent references and availability notes are in the field guide.</p><a href="?view=standings#special-missions">Explore epic arc &amp; COSMOS →</a></div></aside><?php endif; ?>
<?php if ($accountView === 'standings'): ?><details open class="dossier-details"><summary>Mission unlocks &amp; relationship progress</summary><p class="note">These are real ordinary-agent standing thresholds. Reaching one relationship’s threshold can qualify agents in its faction or corporation; agent-specific blockers still apply.</p>
<div class="dossier-track-list"><?php foreach ($dashboard['mission_tracks'] as $entry): ?><article><div><strong><?= eve_e($entry['name'] ?? ('EVE ID ' . $entry['from_id'])) ?></strong><span>Raw <?= number_format($entry['standing'], 2) ?><?= isset($entry['effective']) ? ' · effective ' . number_format($entry['effective'], 2) : ' · effective unavailable' ?></span></div>
<?php if ($entry['mission_levels'] === []): ?><p class="note">No ordinary level 2–5 agents are recorded for this corporation. No mission unlock is claimed.</p><?php else: ?><ul class="dossier-milestones"><?php foreach ($entry['mission_levels'] as $level): $threshold = [2 => 1, 3 => 3, 4 => 5, 5 => 7][$level]; $effective = $entry['effective'] ?? null; ?><li class="<?= $effective !== null && $effective >= $threshold ? 'reached' : '' ?>"><strong>Level <?= $level ?></strong><span>+<?= $threshold ?> effective</span><small><?= $effective === null ? 'Skills required' : ($effective >= $threshold ? 'Threshold met' : number_format($threshold - $effective, 2) . ' to go') ?></small></li><?php endforeach; ?></ul><?php endif; ?></article><?php endforeach; ?></div>
<p class="note">Faction standing broadens access across Guristas corporations. Corporation standing can already qualify you for higher-level work even if your faction track is lower.</p></details>
<details open class="dossier-details" id="guristas-agent-options"><summary>Guristas mission options · <?= count($guristas['opportunities']) ?> suggested agents</summary>
<p class="note">A shortlist, not a nearest-agent recommendation. Bases come from static reference data. Nullsec travel and ship preparation require your judgment.</p><div class="guristas-agent-cards">
<?php foreach ($guristas['opportunities'] as $agent): ?><article><div class="pilot-entity"><img class="pilot-entity-icon" src="https://images.evetech.net/characters/<?= $agent['id'] ?>/portrait?size=64" alt="" width="40" height="40" loading="lazy"><h4><?= eve_e($agent['name']) ?></h4></div><p>Level <?= $agent['agent_level'] ?> · <?= eve_e($agent['division_name'] ?? 'Division not recorded') ?><br><?= eve_e($agent['corporation_name'] ?? 'Guristas') ?><br><?= eve_e($pilotData['entity_names'][$agent['station_id'] ?? 0] ?? $agent['location_name']) ?></p>
<p class="agent-access-state"><?php if ($agent['state'] === 'eligible'): ?>Standing requirements met<?php elseif ($agent['state'] === 'incomplete'): ?>Check access first · personal relationship not fully reported<?php elseif ($agent['state'] === 'level_one'): ?>No positive standing needed<?php elseif ($agent['state'] === 'check_blocker'): ?>Blocking relationship<?= !$agent['calculated'] ? ' · skills unavailable' : '' ?><?php elseif ($agent['state'] === 'threshold_met'): ?>Raw threshold met · skills unavailable<?php elseif ($agent['state'] === 'unknown'): ?>Standing not reported<?php else: ?>Work toward +<?= $agent['threshold'] ?> effective standing<?php endif; ?></p>
<details><summary>Agent profile &amp; access details</summary><ul class="note"><?php foreach ($agent['evidence'] as $evidence): ?><li><?= eve_e($evidence['name']) ?>: raw <?= number_format($evidence['raw'], 2) ?> → <?= $agent['calculated'] ? 'effective' : 'reported' ?> <?= number_format($evidence['effective'], 2) ?> · <?= eve_e($evidence['skill']) ?> <?= $evidence['level'] ?><?= $evidence['effective'] <= -2 ? ' · blocker' : ($evidence['effective'] >= $agent['threshold'] ? ' · qualifies' : '') ?></li><?php endforeach; ?></ul><p>Profile: <?= eve_e($agent['race_name'] ?? 'Race not recorded') ?> · <?= !empty($agent['is_locator']) ? 'Locator service recorded' : 'No locator service recorded' ?>.<br>Corporation: <?= eve_e($agent['corporation_name'] ?? 'Guristas') ?> · Faction: Guristas Pirates.</p><p class="note">Official reference data has no biography for this agent. Search this name in EVE and use Show Info to check current mission access.</p><small>Agent ID <?= $agent['id'] ?>. Confirm availability and other restrictions in EVE.</small></details></article><?php endforeach; ?></div></details>
<?php require __DIR__ . '/pilot-special-missions.php'; ?><?php endif; ?><?php if ($accountView === 'standings'): ?><details class="dossier-details"><summary>How standings, skills &amp; rewards work</summary><p>Ordinary missions build agent and corporation trust. Faction-rewarding activities, including storyline missions, build faction trust. Social improves gains; Diplomacy and Criminal Connections adjust effective standings. Enlistment uses the raw faction relationship.</p><p class="note">Ordinary level 2–5 access uses the highest applicable effective relationship, with none at −2 or lower. Special, storyline and epic-arc agents have separate rules. Unreported relationships remain unknown.</p>
<?php if ($dashboard['skills'] !== null): ?><p class="note">Active Diplomacy <?= $dashboard['skills'][3357] ?> · Criminal Connections <?= $dashboard['skills'][3361] ?>. Skills retrieved <?= eve_e($pilotData['skills']['meta']['fetched_at'] ?? 'Unknown') ?>; expires <?= eve_e($pilotData['skills']['meta']['expires_at'] ?? 'Unknown') ?>.</p><?php else: ?><p class="note">Skill adjustments unavailable because skills or standings are missing or stale. <a href="/auth/start.php">Sign in again</a> if permission is missing.</p><?php endif; ?><p><a href="https://support.eveonline.com/hc/en-us/articles/203217152-Standings" target="_blank" rel="noopener noreferrer">Official EVE standing rules ↗</a></p></details><?php endif; ?>
</div>
