<?php
require_once dirname(__DIR__, 2) . '/services/PilotRomance.php';
$romance = $pilotData['romance'] ?? null; $chapters = eve_romance_chapters();
?>
<section class="account-panel dossier-story"><p class="eyebrow">PRIVATE FREQUENCY // ROMANCE</p><div class="dossier-agent-intro"><img src="/assets/images/dossier/contact.svg" width="72" height="72" alt="Illustrated contact icon"><div><h2>Ren Vey</h2><p>An adult Guristas courier with a life beyond the cargo manifest.</p><small>Original Guristas.net character · optional fan fiction · private to your account</small></div></div>
<?php if ($romance === null): ?><p role="status">Your story record is temporarily unavailable. No progress has been reset.</p>
<?php elseif (!$romance['enabled']): ?><p>A three-scene pilot story about trust, vulnerability and choosing what comes next. Choices change affinity and the ending. This does not change EVE standings or agent access.</p><form method="post"><input type="hidden" name="csrf" value="<?= eve_e(eve_csrf()) ?>"><button name="action" value="romance_start"><?= $romance['chapter'] ? 'Resume story' : 'Open the private frequency' ?></button></form>
<?php else: ?><p>Affinity <strong><?= (int)$romance['affinity'] ?> / 100</strong> · <?= min(3, (int)$romance['chapter']) ?> / 3 scenes completed</p><progress max="100" value="<?= (int)$romance['affinity'] ?>" aria-label="Ren Vey affinity"></progress>
<?php if ($romance['chapter'] < count($chapters)): $chapter = $chapters[$romance['chapter']]; ?><h3><?= eve_e($chapter['title']) ?></h3><p class="dossier-story-dialogue"><?= eve_e($chapter['text']) ?></p><form method="post" class="dossier-story-choices"><input type="hidden" name="csrf" value="<?= eve_e(eve_csrf()) ?>"><input type="hidden" name="action" value="romance_choice"><input type="hidden" name="chapter" value="<?= (int)$romance['chapter'] ?>"><?php foreach ($chapter['choices'] as $key => $option): ?><button name="choice" value="<?= eve_e($key) ?>"><?= eve_e($option[0]) ?></button><?php endforeach; ?></form>
<?php else: ?><h3><?= end($romance['choices']) === 'friends' ? 'A trusted friend' : ($romance['affinity'] >= 80 ? 'A shared horizon' : 'Room to grow') ?></h3><p><?= end($romance['choices']) === 'friends' ? 'Ren smiles. “Friends, then. No debts, no expectations. Just a place saved for you.”' : ($romance['affinity'] >= 80 ? 'Ren takes your hand. “Then let’s make a little room for us. One honest moment at a time.”' : 'Ren nods. “We don’t have to rush. I’m glad we started talking.”') ?></p><p class="note">This story is complete. Your choices and relationship recognition are saved.</p><?php endif; ?>
<form method="post"><input type="hidden" name="csrf" value="<?= eve_e(eve_csrf()) ?>"><button name="action" value="romance_pause">Pause story and keep progress</button></form>
<?php endif; ?><p><a href="?view=achievements">View relationship achievements →</a></p></section>
