<?php
$insurgencyAdvice = $insurgencyAdvice ?? ['phase' => 'unavailable'];
$campaign = $insurgencyAdvice['campaign'] ?? []; $warTarget = $insurgencyAdvice['target'] ?? null;
?>
<article class="dossier-action dossier-illustrated"><img class="dossier-action-icon" src="/assets/images/dossier/insurgency.svg" width="72" height="72" alt=""><div><p class="eyebrow">NEXT FW ACTION</p>
<?php if (!$dashboard['fw_ready']): ?><h4>Restore your enlistment feed</h4><p>Sign in again if access was revoked. Membership must be known before sending you into pirate service.</p>
<?php elseif (!$dashboard['enlisted']): ?><h4>Prepare for Guristas service</h4><p>Check Guristas enlistment requirements in the Insurgencies window. Campaign intelligence is available in Faction Warfare.</p>
<?php elseif ($insurgencyAdvice['phase'] === 'active'): ?>
<h4><?= $warTarget ? 'Review opportunities in ' . eve_e($warTarget['name']) : 'Compare current insurgency opportunities' ?></h4>
<p>Guristas campaign <?= (int)($campaign['id'] ?? 0) ?> · FOB: <strong><?= eve_e($campaign['origin_name'] ?? 'Not reported') ?></strong> · <?= (int)($insurgencyAdvice['won_systems'] ?? 0) ?> / <?= eve_e((string)($campaign['corruption_target'] ?? '?')) ?> systems at corruption 5.</p>
<?php if ($warTarget): ?><p>Reported corruption: stage <?= (int)$warTarget['corruption_stage'] ?> · <?= number_format($warTarget['corruption_percent'], 2) ?>%. Suppression: stage <?= (int)$warTarget['suppression_stage'] ?>.</p><p><?= ($insurgencyAdvice['goal'] ?? '') === 'spread' ? 'Build this system to corruption stage 3 to enable spread. Clear pirate insurgency complexes here; Large ADV-1 now respawns in the same system every 40 minutes.' : 'This system has reached the spread threshold. Push toward corruption 5 to help reach the campaign’s system-win target.' ?> Select an ADV complex that admits your hull and coordinate with a Guristas fleet.</p><details><summary>Why this system?</summary><p class="note"><?= eve_e($insurgencyAdvice['selection_reason'] ?? '') ?></p><p><?= (int)($warTarget['jumps'] ?? 0) ?> shortest-route stargate jumps from your reported location. Confirm travel, eligible sites and opposition in EVE before undocking.</p></details><?php else: ?><p>Your distance to campaign systems is unavailable, or no unfinished system qualifies. Use the map to compare local options; no destination is assumed best.</p><?php endif; ?>
<?php if (!empty($insurgencyAdvice['alternatives'])): ?><details><summary>Other campaign options</summary><ul><?php foreach ($insurgencyAdvice['alternatives'] as $option): ?><li><?= eve_e($option['name']) ?> · <?= $option['jumps'] === null ? 'travel unknown' : (int)$option['jumps'] . ' jumps' ?> · corruption <?= (int)$option['corruption_stage'] ?> · suppression <?= (int)$option['suppression_stage'] ?></li><?php endforeach; ?></ul></details><?php endif; ?>
<details><summary>Rewards and preparation</summary><p>Choose an ADV site that admits your current hull. Site LP and personal campaign contribution both matter. A win pays a 1× contribution multiplier and a loss 0.4×; the maximum winning payout is 1.5 million LP at 45% personal contribution. Your actual contribution and expected earnings are not available here. Career victory points are a separate measure.</p><p>For unknown readiness, contested sites or an unsuitable hull, coordinate with a Guristas fleet or choose a lower-demand eligible site. Do not move just because a system is close to winning.</p></details>
<?php elseif ($insurgencyAdvice['phase'] === 'forecast'): ?><h4>Prepare for the forecast at <?= eve_e($campaign['origin_name'] ?? 'the next FOB') ?></h4><p><?= !empty($insurgencyAdvice['expected_start']) ? 'Estimated live start: ' . eve_e(gmdate('j M Y H:i', strtotime($insurgencyAdvice['expected_start']))) . ' EVE time (UTC).' : 'A start time has not been reported.' ?> This estimate uses the 48-hour forecasting period; confirm the countdown in EVE.</p>
<?php elseif ($insurgencyAdvice['phase'] === 'none'): ?><h4>Prepare for the next Guristas insurgency</h4><p>No active or forecast Guristas campaign is reported. The next location and start time have not been announced in this feed.</p>
<?php else: ?><h4>Check the current insurgency in EVE</h4><p>A fresh campaign feed is unavailable. Open Insurgencies in EVE before choosing a destination.</p><?php endif; ?>
<a href="/war/guristas/overlay/">Open the Guristas war map →</a></div></article>
