<?php
$progress=CommunityNetwork::progress($ledger,$entry['id']);
?>
<section class="tool-card"><h2>Supply order</h2><p><strong>Item:</strong> <?= escape($entry['item']??'See organizer instructions') ?></p>
<?php if($progress['target']): ?><p><strong>Requested:</strong> <?= number_format($progress['target']) ?> units · <strong>Verified:</strong> <?= number_format($progress['verified']) ?> · <strong>Reserved or awaiting review:</strong> <?= number_format($progress['held']) ?> · <strong>Available:</strong> <?= number_format($progress['available']) ?></p><progress max="<?= $progress['target'] ?>" value="<?= min($progress['target'],$progress['verified']) ?>" aria-label="Verified delivery progress"><?= $progress['verified'] ?> of <?= $progress['target'] ?></progress><p><strong>Reward:</strong> <?= escape($entry['reward']??'0') ?> ISK per unit. <?= escape($entry['terms']??'') ?></p><?php else: ?><p>The organizer has not set a quantity target. Confirm the request directly. Historical delivery reviews count as records, not verified item quantities.</p><?php endif; ?>
<p class="note">Confirm the order and payment terms with <?= escape($entry['contact']) ?> before hauling. A reservation records your intended delivery; it does not issue a contract or transfer ISK. Submit evidence for the whole reserved quantity before it expires. Cancel and reserve a smaller quantity if your plan changes.</p>
<?php
$open=$entry['status']==='published' && ($entry['when']==='' || $entry['when']>gmdate('Y-m-d\TH:i'));
$active=[];
if($viewer)$active=array_filter($ledger['claims'],fn($c)=>$c['entry']===$entry['id'] && $c['actor']===(int)$viewer['character_id'] && ($c['status']==='pending' || ($c['status']==='reserved' && $c['expires']>time())));
?>
<?php if(!$open): ?><p>This job is closed to new reservations. Existing deliveries can still be reviewed.</p><?php elseif(!$viewer): ?><p>Sign in through the main login to reserve a delivery quantity.</p><?php elseif(!$active && $progress['target'] && $progress['available']): ?><form method="post" action="/community/delivery.php"><input type="hidden" name="csrf" value="<?= escape(eve_csrf()) ?>"><input type="hidden" name="revision" value="<?= (int)$ledger['revision'] ?>"><input type="hidden" name="action" value="reserve"><input type="hidden" name="id" value="<?= escape($entry['id']) ?>"><label>Units you will deliver<input type="number" name="quantity" min="1" max="<?= $progress['available'] ?>" step="1" required></label><button class="primary-button">Reserve this quantity</button><p class="note">Expires after 48 hours or at the job deadline, whichever is earlier.</p></form><?php elseif($progress['target'] && !$progress['available']): ?><p>The target is filled or reserved. Check other posted jobs.</p><?php elseif($viewer && !$progress['target'] && !$active): ?><form method="post" action="/community/delivery.php"><input type="hidden" name="csrf" value="<?= escape(eve_csrf()) ?>"><input type="hidden" name="revision" value="<?= (int)$ledger['revision'] ?>"><input type="hidden" name="action" value="submit"><input type="hidden" name="id" value="<?= escape($entry['id']) ?>"><label>Private delivery evidence<textarea name="evidence" required maxlength="3000" placeholder="Contract ID, quantity, EVE time and recipient."></textarea></label><button class="secondary-button">Submit for review</button></form><?php endif; ?>
<?php foreach($active as $claim): require __DIR__.'/supply-record.php'; endforeach; ?>
</section>
