<?php
$pageTitle = 'Guristas Missions & Agents';
$pageDescription = 'Find your first contact, check the mission level, and discover the epic arc and COSMOS chains. The field guide is open to every capsuleer.';
$navActive = 'missions';
require dirname(__DIR__, 2) . '/app/views/partials/public-tool-header.php';
require_once dirname(__DIR__, 2) . '/app/services/PilotEntityNames.php';
$query = is_string($_GET['q'] ?? null) ? substr(trim($_GET['q']), 0, 120) : '';
$level = is_string($_GET['level'] ?? null) && in_array($_GET['level'], ['1','2','3','4','5','special'], true) ? $_GET['level'] : '';
$agents = [];
foreach (eve_pilot_entity_catalog() as $id => $agent) {
    if (($agent['kind'] ?? '') !== 'agent' || ($agent['faction_id'] ?? null) !== 500010) continue;
    $special = ($agent['agent_type_id'] ?? null) !== 2;
    if ($level !== '' && ($level === 'special' ? !$special : ($special || (string)($agent['agent_level'] ?? '') !== $level))) continue;
    $haystack = implode(' ', [$agent['name'], $agent['corporation_name'] ?? '', $agent['system_name'] ?? '', $agent['division_name'] ?? '']);
    if ($query !== '' && stripos($haystack, $query) === false) continue;
    $agents[(int)$id] = $agent;
}
uasort($agents, static function ($a, $b) { return (($a['agent_level'] ?? 0) <=> ($b['agent_level'] ?? 0)) ?: strcasecmp($a['name'], $b['name']); });
?>
<section class="tool-card tool-callout"><img src="/assets/images/dossier/contact.svg" alt="" width="64" height="64"><div><h2>Start with a contact you can actually use</h2><p>For ordinary missions, start with level 1 if you are building trust. Moving to a higher level requires both agent access and a ship you can realistically use. Standing alone does not make you ready.</p><div class="tool-buttons"><a href="?level=1#agent-directory">Find level 1 agents</a><a href="/account/?view=overview">Check my access and hull readiness</a></div></div></section>
<div class="tool-grid"><article class="tool-card" id="epic-arc"><div class="agent-name"><img src="https://images.evetech.net/characters/3019464/portrait?size=128" alt="Portrait of Yada Vinjivas" width="64" height="64"><h2>Guristas epic arc</h2></div><p>A major Guristas mission chain with faction-standing rewards. Yada Vinjivas in Taisy is one recorded starter contact.</p><p>Open The Agency → Agents &amp; Missions → Epic Arcs to check your available route and cooldown before travelling. Special starter rules differ from ordinary agents.</p><a href="https://support.eveonline.com/hc/en-us/articles/360009908300-Epic-Arc" target="_blank" rel="noopener noreferrer">Official arc guide ↗</a></article>
<article class="tool-card" id="cosmos"><div class="agent-name"><img src="/assets/images/dossier/missions.svg" alt="" width="64" height="64"><h2>Guristas COSMOS</h2></div><p>Special mission chains with their own prerequisites. Read the full chain before accepting an offer and confirm access with the agent in EVE.</p><p class="tool-note">ESI does not provide your epic-arc cooldown or COSMOS completion history. Signing in cannot verify those missing records.</p><a href="https://wiki.eveuniversity.org/Guristas_COSMOS" target="_blank" rel="noopener noreferrer">COSMOS field reference ↗</a></article></div>
<section class="tool-card" id="agent-directory"><h2>Choose a contact</h2><p>Compare level and base. Use EVE's route planner before setting out. A shorter route may still pass through dangerous space.</p><form method="get" action="/missions/" class="tool-controls"><label>Agent, system or corporation<input name="q" value="<?= escape($query) ?>" maxlength="120" placeholder="Try Aakie, Haatoluppa or a system"></label><label>Mission level<select name="level"><option value="">All contacts</option><?php foreach (['1'=>'Level 1','2'=>'Level 2','3'=>'Level 3','4'=>'Level 4','5'=>'Level 5','special'=>'Special agents'] as $key=>$label): ?><option value="<?= $key ?>" <?= $level === (string)$key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></label><div class="tool-buttons"><button type="submit">Find contacts</button><a href="/missions/#agent-directory">Reset</a></div></form>
<p role="status"><?= count($agents) ?> matching contacts. Static reference retrieved October 6, 2026.</p><div class="tool-table-wrap"><table class="tool-table"><caption>Public Guristas agent reference</caption><thead><tr><th scope="col">Contact</th><th scope="col">Base</th><th scope="col">Access</th></tr></thead><tbody>
<?php foreach ($agents as $id => $agent): $special = ($agent['agent_type_id'] ?? null) !== 2; $missionLevel = (int)($agent['agent_level'] ?? 0); ?>
<tr><th scope="row"><div class="agent-name"><img src="https://images.evetech.net/characters/<?= $id ?>/portrait?size=64" alt="" width="48" height="48" loading="lazy"><div><?= escape($agent['name']) ?><small><?= escape($agent['corporation_name'] ?? '') ?></small><small><?= $special ? 'Special agent' : 'Level ' . $missionLevel ?> · <?= escape($agent['division_name'] ?? 'Unknown division') ?></small></div></div></th><td><?= escape($agent['system_name'] ?? 'Not recorded') ?><small><br><?= escape($agent['location_name'] ?? '') ?><?php if (isset($agent['station_id'])): ?><br>Station ID <?= (int)$agent['station_id'] ?><?php endif; ?></small></td><td><?= $special ? 'Check individual prerequisites in EVE.' : ($missionLevel === 1 ? 'No positive standing required for ordinary level 1 access.' : '+' . ([2=>1,3=>3,4=>5,5=>7][$missionLevel] ?? '?') . ' effective agent, corporation or faction standing; check restrictions in EVE.') ?></td></tr>
<?php endforeach; ?></tbody></table></div><?php if ($agents === []): ?><p>No contacts match. Clear the search or try another level.</p><?php endif; ?>
<details><summary>How access works</summary><p>Ordinary level 2–5 agents use applicable effective standings and relationship restrictions. Special agents have separate rules. Your dossier checks reported standings and skills; this directory does not claim you are eligible.</p><p>Level and division describe the agent, not a promise that every mission can be completed in a particular hull. Check the offered mission and keep a fallback contact at a lower level.</p><a href="https://support.eveonline.com/hc/en-us/articles/203217152-Standings" target="_blank" rel="noopener noreferrer">Official standing rules ↗</a></details></section>
<?php require dirname(__DIR__, 2) . '/app/views/partials/public-tool-footer.php'; ?>
