<?php
$pageTitle = 'Enlist with the Guristas';
$pageDescription = 'Your first assignment is simple: check access, enlist, and prepare one affordable sortie. Corporation membership is your choice.';
$navActive = 'join';
require dirname(__DIR__, 2) . '/app/views/partials/public-tool-header.php';
?>
<section class="tool-card tool-callout"><img src="/assets/images/dossier/insurgency.svg" width="64" height="64" alt=""><div><h2>Commando Guri needs capsuleers</h2><p>You can support the Guristas without joining Cozen Corp or signing into this website. Use the steps below in EVE. Sign in here when you want personal progress and recommendations.</p><a href="/war/guristas/">Read the current campaign →</a></div></section>
<div class="tool-grid"><section class="tool-card"><h2>01 · Check your standing</h2><p>Current pirate enlistment requires at least <strong>0.0 base faction standing</strong>. Skills that change effective standings do not replace the base requirement.</p><p>Check your Guristas standing in EVE. If it is too low, use the mission field guide to plan how to improve it.</p><a href="/missions/">Find a mission contact →</a><p class="tool-note">Some older support text still says −2.0. The later patch notes raise the requirement to 0.0.</p><a href="https://www.eveonline.com/news/view/patch-notes-version-23-01" target="_blank" rel="noopener noreferrer">Enlistment change source ↗</a></section>
<section class="tool-card"><h2>02 · Enlist in EVE</h2><p>Open the warfare or Insurgencies interface in your Neocom and choose the Guristas. Review the warnings and current eligibility before confirming.</p><p>Direct enlistment may let you keep your existing corporation if its settings allow it. Joining the NPC militia and joining a player corporation are different choices.</p><p>Enlistment changes whom you can fight and where you face threats. Check your travel plans before flying into hostile empire space.</p></section>
<section class="tool-card"><h2>03 · Take one manageable sortie</h2><p>Choose a hull you can fly and afford to replace. Check site eligibility, ammunition, drones and your exit route. Start small, then learn from the result.</p><p>If the campaign is between rounds, use that time for training, missions and resupply. There is no need to invent a target while no active campaign is reported.</p><div class="tool-buttons"><a href="/ships/">Compare ships</a><a href="/war/guristas/">Open War Room</a></div></section></div>
<section class="tool-card" id="cozen"><h2>Want company? Meet Cozen Corp</h2><p>Cozen Corp is Kniraven's Guristas-aligned corporation. If you want to fly with this community, look up <strong>Cozen Corp</strong> in EVE's corporation search and contact <strong>Kniraven</strong> in EVE.</p><p>Ask about current recruitment, time zones, fleet expectations and how you can help The Fulcrum. Confirm availability before moving assets or applying. This page does not promise a fleet schedule or membership approval.</p><p class="tool-note">Joining Cozen is optional. Guristas enlistment, website access and corporation membership are separate decisions.</p></section>
<?php require dirname(__DIR__, 2) . '/app/views/partials/public-tool-footer.php'; ?>
