<?php
$pageTitle = 'Black Rabbit Radio';
$pageDescription = 'Tune into the Guristas signal: music, Kniraven broadcasts and intercepted Federation reports. No sign-in required.';
$navActive = 'signals';
require dirname(__DIR__, 2) . '/app/views/partials/public-tool-header.php';
?>
<section class="tool-card radio-deck" id="radio" data-radio><div class="agent-name"><img src="/assets/images/dossier/romance.svg" width="64" height="64" alt=""><div><p class="eyebrow">FAN MUSIC // DEMO ARCHIVE</p><h2>Choose your transmission</h2></div></div><p>Recovered Guristas fan-music demos. Press play when you are ready; the relay will not start sound on its own.</p>
<div class="tool-buttons"><button type="button" data-radio-track="/assets/audio/fatal-mistake-demo.mp3" data-track-title="Fatal Mistake · alternate rock demo">Fatal Mistake</button><button type="button" data-radio-track="/assets/audio/black-rabbits-demo.mp3" data-track-title="Black Rabbits · alternate rock demo">Black Rabbits</button></div>
<p data-radio-status role="status">Selected: Fatal Mistake · alternate rock demo</p><audio controls preload="none" data-radio-player src="/assets/audio/fatal-mistake-demo.mp3">Your browser does not support audio playback. Download a track below.</audio>
<label class="tool-note"><input type="checkbox" data-radio-motion> Show playback animation</label><div class="radio-bars" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>
<p class="tool-note">Fan-made demos from Kniraven's Guristas music project, recovered from the existing archive. These are not official EVE releases.</p>
<details><summary>Fatal Mistake lyrics</summary><div class="radio-lyrics"><?= nl2br(escape((string)file_get_contents(dirname(__DIR__, 2) . '/app/data/fatal-mistake-lyrics.txt'))) ?></div><p class="tool-note">Companion lyric sheet for this demo; no synchronized timing is provided.</p></details>
<div class="tool-buttons"><a href="/assets/audio/fatal-mistake-demo.mp3" download>Download Fatal Mistake</a><a href="/assets/audio/black-rabbits-demo.mp3" download>Download Black Rabbits</a></div></section>
<div class="tool-grid"><section class="tool-card" id="broadcast"><h2>Kniraven on Twitch</h2><p>Watch the channel here, or open Twitch for its current status, videos and schedule.</p><div data-twitch-player></div><div class="tool-buttons"><button type="button" data-load-twitch>Load Twitch player</button><a href="https://www.twitch.tv/kniraven" target="_blank" rel="noopener noreferrer">Open channel ↗</a></div><p class="tool-note">Loading the player connects to Twitch. If the embed is unavailable, use the channel link.</p></section>
<section class="tool-card" id="archive"><h2>Missed a transmission?</h2><p>Browse recordings that remain available on Kniraven's Twitch channel. Twitch controls retention and availability.</p><a href="https://www.twitch.tv/kniraven/videos" target="_blank" rel="noopener noreferrer">Browse channel recordings ↗</a><p class="tool-note">A permanent local episode archive needs the selected recording files or episode links. We do not list invented episodes.</p></section>
<section class="tool-card"><p class="eyebrow">INTERCEPTED SIGNAL // THEATRICAL RP</p><h2>Federation Front Line Report</h2><p>Hear the Gallente side of the warzone, then form your own judgement. Our rivalry is roleplay.</p><div class="tool-buttons"><a href="https://federationfrontlinereport.com/podcast" target="_blank" rel="noopener noreferrer">Open the podcast archive ↗</a><a href="https://www.twitch.tv/federationfrontlinereport" target="_blank" rel="noopener noreferrer">Open broadcast channel ↗</a></div></section></div>
<script src="/assets/js/public-radio.js?v=<?= filemtime(dirname(__DIR__) . '/assets/js/public-radio.js') ?>" defer></script>
<?php require dirname(__DIR__, 2) . '/app/views/partials/public-tool-footer.php'; ?>
