<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
$arguments=array_slice($argv,1);
if (array_diff($arguments,['--apply'])) { fwrite(STDERR,"Usage: php scripts/cleanup-cache.php [--apply]\n"); exit(1); }
$apply=in_array('--apply',$arguments,true);
$root=dirname(__DIR__);
$config=require $root.'/config/esi.php';
// Preserve expiry plus at least one day, exceeding the configured stale-error window.
$grace=max(86400,(int)($config['stale_if_error_seconds'] ?? 3600));
$now=time();
$counts=['eligible'=>0,'removed'=>0,'preserved'=>0,'skipped'=>0];
try {
    foreach (['esi','derived','frontlines'] as $folder) {
        $directory=$root.'/storage/cache/'.$folder;
        if (!is_dir($directory)) continue;
        if (is_link($root.'/storage') || is_link($root.'/storage/cache') || is_link($directory)) throw new RuntimeException('Refusing a linked cache directory: '.$folder);
        foreach (new DirectoryIterator($directory) as $file) {
            if ($file->isDot()) continue;
            if ($file->isLink() || !$file->isFile() || !preg_match('/^[a-f0-9]{64}\.json$/D',$file->getFilename())) { $counts['skipped']++; continue; }
            $path=$file->getPathname();
            $original=file_get_contents($path);
            if ($original===false) throw new RuntimeException('Cannot read cache entry: '.$path);
            $entry=json_decode($original,true);
            if (!is_array($entry) || !isset($entry['expires_at']) || !is_numeric($entry['expires_at'])) { $counts['skipped']++; continue; }
            if ((int)$entry['expires_at']+$grace >= $now) { $counts['preserved']++; continue; }
            $counts['eligible']++;
            echo ($apply?'REMOVE ':'WOULD REMOVE ').$folder.'/'.$file->getFilename().PHP_EOL;
            if ($apply) {
                // Skip files refreshed since inspection. Atomic cache writers may still race
                // this final check; a deleted cache can be regenerated by the next request.
                clearstatcache(true,$path);
                if (is_link($path) || !is_file($path) || file_get_contents($path)!==$original) { $counts['skipped']++; continue; }
                if (!unlink($path)) throw new RuntimeException('Cannot remove cache entry: '.$path);
                $counts['removed']++;
            }
        }
    }
    echo json_encode(['mode'=>$apply?'apply':'preview','grace_hours'=>$grace/3600,'counts'=>$counts],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR).PHP_EOL;
} catch (Throwable $error) { fwrite(STDERR,$error->getMessage().PHP_EOL); exit(1); }
