<?php
$pageTitle = 'Guristas War Room';
$pageDescription = 'Find the campaign. Pick a manageable objective. Keep your ship, earn your cut, and help the Guristas advance.';
$navActive = 'war';
require dirname(__DIR__, 3) . '/app/views/partials/public-tool-header.php';
?>
<section class="tool-card tool-callout"><img src="/assets/images/dossier/insurgency.svg" alt="" width="64" height="64"><div><h2>Take a useful fight, not an expensive gamble</h2><p>Start with an eligible site you can complete in a hull you can afford to replace. Check the local situation in EVE. Campaign progress matters, but losing ships faster than you earn rewards does not help your wallet.</p><div class="tool-buttons"><a href="/join/">New to pirate warfare? Start here</a><a href="/account/">Use my pilot record</a></div></div></section>
<section class="tool-card" data-campaign><h2>Campaign watch</h2><p class="tool-status" data-campaign-status role="status">Contacting the warzone relay…</p><p data-campaign-detail></p><p class="tool-note" data-campaign-freshness></p><div class="tool-buttons"><button type="button" data-campaign-refresh>Refresh report</button><a href="https://www.eveonline.com/frontlines" target="_blank" rel="noopener noreferrer">Official war report ↗</a></div><noscript><p>JavaScript is needed for this live report. Use the official war report or the Insurgencies window in EVE.</p></noscript>
<div class="tool-controls"><label>Find a system<input type="search" data-campaign-search placeholder="System name"></label><label>Show<select data-campaign-filter><option value="all">All reported systems</option><option value="push">Can still advance</option><option value="spread">Below spread stage 3</option><option value="won">Corruption stage 5</option></select></label></div>
<p class="tool-note" data-campaign-count></p><div data-campaign-map></div><p class="tool-note">Map is a stargate schematic, not a safe route or shipcaster route. The list remains available if coordinates cannot be plotted.</p>
<div class="tool-table-wrap"><table class="tool-table"><caption>Reported insurgency systems</caption><thead><tr><th scope="col">System</th><th scope="col">Corruption stage</th><th scope="col">Suppression stage</th><th scope="col">Status</th></tr></thead><tbody data-campaign-systems></tbody></table></div></section>
<div class="tool-grid"><section class="tool-card"><h2>Make your next sortie count</h2><ol><li>Confirm you are enlisted with Commando Guri.</li><li>Read the site restrictions before entering. Pirate hulls do not fit every site.</li><li>Check local, directional scan and the exit route. Recheck while inside.</li><li>Complete the objective, then review LP earned, losses and contribution in EVE.</li></ol><p>When a site is crowded or hostile, try another eligible site or nearby campaign system. You do not need to take every fight.</p><a href="/ships/">Compare hulls →</a></section>
<section class="tool-card"><h2>Campaign progress and your payout</h2><p>Sites earn LP and contribute to the campaign. The final reward also depends on your contribution and the outcome. Check your contribution meter in EVE before deciding whether to keep pushing.</p><p>Winning at maximum contribution can pay 1,500,000 LP. Maximum contribution requires 45% personal corruption or suppression; the losing multiplier is 0.4.</p><p class="tool-note">The public feed does not expose your personal contribution, site occupancy, opposition or achievable LP per hour.</p><a href="https://www.eveonline.com/news/view/patch-notes-version-24-01" target="_blank" rel="noopener noreferrer">Current rule source ↗</a></section>
<section class="tool-card"><h2>Help the insurgency spread</h2><p>Corruption stage 3 unlocks spread. Groups can use the static Large ADV-1 site, with its 40-minute respawn, to apply pressure in a chosen system.</p><p>For an organized push, compare systems below stage 3, opposition and the fleet's objective. Coordinate the target with your commander. Completing one site does not guarantee which neighboring system will be added.</p><p class="tool-note">These are strategic considerations, not an automatic order. The report does not tell us where enemy fleets are waiting.</p></section></div>
<?php require dirname(__DIR__, 3) . '/app/views/partials/public-tool-footer.php'; ?>
