<?php
declare(strict_types=1);
require_once dirname(__DIR__,3).'/app/services/TicketService.php';require_once dirname(__DIR__,3).'/app/services/CommunityWeb.php';
header('Cache-Control: private, no-store');community_post_limit();$user=eve_require_user();$actor=(int)$user['character_id'];
if(!tickets_staff($actor)){http_response_code(403);exit('Staff access required.');}
$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    eve_require_csrf($_POST['csrf']??null);
    try {community_network()->apply($_POST,$actor,(string)$user['character_name'],true);header('Location: /admin/community/',true,303);exit;}
    catch(Throwable $e){$message=community_message($e);}
}
try{$ledger=community_network()->read();}catch(Throwable $e){http_response_code(503);exit('Community ledger unavailable.');}
$key=is_string($_GET['edit']??null)?$_GET['edit']:'';
$defaults=['id'=>'','type'=>'fleet','status'=>'draft','title'=>'','body'=>'','when'=>'','location'=>'','contact'=>'','credit'=>'','url'=>'','item'=>'','quantity'=>'','reward'=>'0','terms'=>'','fleet'=>'','campaign'=>'','campaign_url'=>'','category'=>'fan-art','review_note'=>'','images'=>[],'public_archive'=>false];
$edit=($ledger['entries'][$key]??[])+$defaults;
if($edit['status']==='pending')$edit['status']='draft';
$pageTitle='Community Publishing';$pageDescription='Publish real operations and approved media. Review evidence before recording verified delivery credit.';$navActive='admin';
$pageAccess='PUBLISHING DESK // STAFF ACCESS';
require dirname(__DIR__,3).'/app/views/partials/public-tool-header.php';
?>
<p class="tool-buttons"><a href="/admin/">Staff desk</a><a href="/operations/">Public operations</a><a href="/community/">Public transmissions</a><a href="/community/submit.php">Upload art / comic pages</a><a href="/admin/community/">New text or linked entry</a></p>
<?php if($message): ?><p role="alert"><?= escape($message) ?> Reload the saved entry before trying again.</p><?php endif; ?>
<section class="tool-card"><h2><?= $edit['id']?'Edit entry':'New entry' ?></h2><p>Fleet notices need eligibility, beginner policy and staging instructions. Supply rewards must name the payer and payment timing. All times are EVE time (UTC).</p>
<?php if($edit['images']): ?><p><a href="/community/read.php?id=<?= escape($edit['id']) ?>&amp;preview=1">Preview the artwork or episode</a></p><p>Submitted by <?= escape($edit['author_name']??'Staff') ?>. Permission declared <?= escape($edit['permission_at']??'') ?>.</p><?php endif; ?>
<form method="post" data-community-editor><input type="hidden" name="csrf" value="<?= escape(eve_csrf()) ?>"><input type="hidden" name="revision" value="<?= (int)$ledger['revision'] ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= escape($edit['id']) ?>">
<label>Type<select name="type"><?php foreach(CommunityNetwork::TYPES as $type): ?><option value="<?= $type ?>" <?= $edit['type']===$type?'selected':'' ?>><?= escape($type) ?></option><?php endforeach; ?></select></label>
<label>Status<select name="status"><?php foreach(['draft','published','archived','rejected'] as $status): ?><option value="<?= $status ?>" <?= $edit['status']===$status?'selected':'' ?>><?= $status ?></option><?php endforeach; ?></select></label>
<label>Title<input name="title" required maxlength="160" value="<?= escape($edit['title']) ?>"></label><label>Instructions / description<textarea name="body" required maxlength="6000" rows="8"><?= escape($edit['body']) ?></textarea></label>
<fieldset data-entry-types="fleet supply"><legend>Operation details</legend><label>Staging / delivery destination<input name="location" maxlength="200" value="<?= escape($edit['location']) ?>"></label><label>Commander / buyer contact<input name="contact" maxlength="200" value="<?= escape($edit['contact']) ?>"></label><label>Departure or supply deadline (UTC)<input type="datetime-local" name="when" value="<?= escape($edit['when']) ?>"></label></fieldset>
<fieldset data-entry-types="supply"><legend>Supply target and payment</legend><p>Use the exact in-game item name. Units are item counts, not cargo volume. Published quantity is the total target, including completed deliveries. Zero reward means no ISK promised. Reservations last at most 48 hours. Once reserved, item, destination and payment terms are fixed; make a new job to change them.</p><label>Item name<input name="item" maxlength="160" value="<?= escape($edit['item']) ?>"></label><label>Target quantity<input type="number" name="quantity" min="1" max="1000000000" step="1" value="<?= escape((string)$edit['quantity']) ?>"></label><label>ISK reward per unit<input name="reward" inputmode="decimal" maxlength="30" value="<?= escape($edit['reward']) ?>"></label><label>Payment terms (payer, verification and timing)<textarea name="terms" maxlength="2000"><?= escape($edit['terms']) ?></textarea></label></fieldset>
<fieldset data-entry-types="art"><legend>Art category</legend><label>Category<select name="category"><option value="fan-art" <?= $edit['category']==='fan-art'?'selected':'' ?>>Fan art</option><option value="propaganda" <?= $edit['category']==='propaganda'?'selected':'' ?>>Fan propaganda</option></select></label></fieldset>
<fieldset data-entry-types="report"><legend>Report relationships</legend><label>Related fleet<select name="fleet"><option value="">Independent report</option><?php foreach($ledger['entries'] as $fleet): if($fleet['type']==='fleet'): ?><option value="<?= escape($fleet['id']) ?>" <?= $edit['fleet']===$fleet['id']?'selected':'' ?>><?= escape($fleet['title'].' / '.$fleet['status']) ?></option><?php endif; endforeach; ?></select></label><label>Historical campaign / system context<input name="campaign" maxlength="200" value="<?= escape($edit['campaign']) ?>" placeholder="Campaign date and affected systems"></label><label>HTTPS campaign record / reference link<input name="campaign_url" maxlength="2000" value="<?= escape($edit['campaign_url']) ?>"></label></fieldset>
<fieldset data-entry-types="art comic broadcast report"><legend>Source and creator credit</legend><label>HTTPS source / external recording link<input name="url" maxlength="2000" value="<?= escape($edit['url']) ?>"></label><label>Public creator credit<input name="credit" maxlength="300" value="<?= escape($edit['credit']) ?>"></label><label><input type="checkbox" name="rights" value="yes"> I have checked permission and creator credit for this media release.</label></fieldset>
<?php if($edit['images']): ?><fieldset><legend>Image descriptions and reading order</legend><?php foreach($edit['images'] as $i=>$image): ?><div class="tool-card"><img data-media-preview src="/community/media.php?id=<?= escape($image['id']) ?>" alt="Page preview <?= $i+1 ?>"><label>Position<input type="number" name="positions[<?= escape($image['id']) ?>]" value="<?= $i+1 ?>" min="1" max="<?= count($edit['images']) ?>" required></label><label>Description / transcript<textarea name="alternatives[<?= escape($image['id']) ?>]" required maxlength="3000"><?= escape($image['alt']) ?></textarea></label></div><?php endforeach; ?></fieldset><?php endif; ?>
<label>Private submission review note<textarea name="review_note" maxlength="1000"><?= escape($edit['review_note']) ?></textarea></label><label><input type="checkbox" name="public_archive" value="yes" <?= $edit['public_archive']?'checked':'' ?>> When archiving this operation, keep its historical detail and verified progress public. This never applies to artwork or comics.</label><button class="primary-button">Save entry</button></form></section>
<section class="tool-section"><h2>Submission queue and existing entries</h2><?php if(!$ledger['entries']): ?><p>No entries yet. Upload approved images or create a text entry above.</p><?php endif; ?><div class="tool-table-wrap"><table class="tool-table"><caption>Community entries</caption><thead><tr><th>Title</th><th>Type</th><th>Status</th></tr></thead><tbody><?php foreach(array_reverse($ledger['entries']) as $entry): ?><tr><th><a href="?edit=<?= escape($entry['id']) ?>"><?= escape($entry['title']) ?></a></th><td><?= escape($entry['type']) ?></td><td><?= escape($entry['status']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="tool-section"><h2>Delivery review</h2><p>Verify the whole reserved quantity in EVE before approving. Reject an incorrect quantity and ask the pilot to reserve and submit the correct amount. Approval records verification and releases no automatic payment. Another officer reviews your own deliveries.</p>
<?php $reviews=array_filter($ledger['claims'],fn($c)=>in_array($c['status'],['pending','approved','rejected'],true)); if(!$reviews): ?><p>No deliveries awaiting or completing review.</p><?php endif; ?>
<?php foreach(array_reverse($reviews) as $claim): ?><article class="tool-card"><h3><?= escape($ledger['entries'][$claim['entry']]['title']??'Supply job') ?></h3><p><?= escape($claim['name']) ?> · character <?= (int)$claim['actor'] ?> · <?= escape($claim['status']) ?><?php if(isset($claim['quantity'])): ?> · <?= number_format($claim['quantity']) ?> units<?php endif; ?></p><p class="community-prose"><?= escape($claim['evidence']) ?></p><p><?= escape($claim['note']) ?></p>
<?php if($claim['status']==='pending' && $claim['actor']!==$actor): ?><form method="post"><input type="hidden" name="csrf" value="<?= escape(eve_csrf()) ?>"><input type="hidden" name="revision" value="<?= (int)$ledger['revision'] ?>"><input type="hidden" name="action" value="review"><input type="hidden" name="id" value="<?= escape($claim['id']) ?>"><label>Decision<select name="status"><option value="approved">Verified whole quantity</option><option value="rejected">Not verified</option></select></label><label>Review note<textarea name="note" maxlength="1000" required></textarea></label><button class="secondary-button">Record decision</button></form><?php elseif($claim['status']==='pending'): ?><p>Another officer must review your own delivery.</p><?php endif; ?></article><?php endforeach; ?></section>
<script src="/assets/js/community-forms.js?v=<?= filemtime(dirname(__DIR__,2).'/assets/js/community-forms.js') ?>" defer></script>
<?php require dirname(__DIR__,3).'/app/views/partials/public-tool-footer.php'; ?>
