CREATE TABLE IF NOT EXISTS guristas_staff (
 character_id BIGINT UNSIGNED PRIMARY KEY,
 granted_by BIGINT UNSIGNED NOT NULL,
 granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (character_id) REFERENCES eve_characters(character_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS guristas_tickets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(180) NOT NULL, summary TEXT NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'Backlog',
 priority VARCHAR(10) NOT NULL DEFAULT 'Normal', category VARCHAR(20) NOT NULL DEFAULT 'Feature',
 assignee_id BIGINT UNSIGNED NULL, creator_id BIGINT UNSIGNED NOT NULL,
 due_date DATE NULL, blocked_reason VARCHAR(500) NOT NULL DEFAULT '',
 subtasks_json LONGTEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 status_since DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 INDEX (status, priority), INDEX (assignee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS guristas_ticket_activity (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 ticket_id BIGINT UNSIGNED NOT NULL, author_id BIGINT UNSIGNED NOT NULL,
 kind VARCHAR(10) NOT NULL, body TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (ticket_id) REFERENCES guristas_tickets(id), INDEX (ticket_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
